### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [ekoki/nidonenne#57]
@ekoki 
MVPレビューお疲れ様でした:tada:

下記の観点でMVPレビューを致します。
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
基本的な部分は実装されているかと思います。
README部分で課題と解決方法の間に課題の解決に対する仮説を加えておきましょう。
そうすることで、READMEを見る際にサービスがわかりやすくなります。
あとは技術を強くする部分はUIをよくしてさらに利用しやすいように技術を盛り込んでいきましょう。

## 静的コードチェックが入っている 
rubocop通ってないかなという箇所がちょっとありそうなので、再度rubocop通しておきましょう。
最低限のコードの見た目は良くなるので、これからもコードの読みやすさを意識するようにしておいてください。

### リファクタ
fat controllerになってる箇所があるので修正しておきましょう。
- answer_forms_controllerのcreateの保存処理はモデルもしくはform objectに切り出しておきましょう
- answer_forms_controllerのlogin_with_token処理はapplication_controllerの方で定義した方がいいですね
- line_botとline_user_controllerの処理は同じような部分があるので、linebot用のサービスクラスを作成して処理を切り出してあげましょう
- questions_controllerのquestion_formsの変数などあまり変数を定義している意味がないものがあるので直しておきましょう。（そのままstrong paramsで問題なさそうです）

### 追加機能
よりユーザが使いやすくなるような機能を実装していきましょう。
- 問題自動作成機能
少し調べれば解けそうな問題と解答を複数問データベースに準備しておき、ボタンクリックだけで問題と回答を作成できる
（ajaxやHotwireあたりの技術を入れましょう）

- まとめて複数日の通知&問題作成ができる機能
Googleカレンダーのように直近１週間や毎週月曜などで通知と問題の作成ができる機能があると利用しやすくなりそうです
（作成前に入力データ確認画面などを挟むと良さそうです）

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記の部分が気になったので修正しておきましょう。
- ログインした後にどこから通知設定や、問題作成をすればいいのかわからなかったので、ヘッダーメニューやTOPページ内に見えるように導線を作成しておきましょう。（ヘッダーに関してはアプリのメイン機能への導線が設定されているのがいいです）
- ログイン画面ではパスワード確認のformはなしで大丈夫です。
- 問題作成の画面で作成失敗時はデータをフォームに残すようにしてください、また全ての問題と回答を作成するようになっているので、注意書きなどしておきましょう。
- カーソルのホバー時のカーソルアイコンがおかしいので全体的に見直しておいてください。（ボタンやリンクにホバーする場合はpointerになるなど）
- 問題解答作成部分に関して、自動で調べればできそうな問題をランダムで作成できるといいかなと思います。（意外と自分で3つほど難易度がちょうどいい問題を考えるのは難しそう）

上記内容を一通り確認いただき、それぞれissueとしてタスクを書き出しましたら、こちらのissueはcloseしてもらって構いません
。
本リリースまで頑張っていきましょう！

**Comment by ekoki** [comment]
@kerochelo 
丁寧にレビュー頂きありがとうございます！
とても勉強になります！
タスクとして書き出しましたので、当該issueはclose致します。
上記につきまして修正し、本リリースまで頑張ります！
引き続きよろしくお願い致します！
